# Simple set of rules for GitHub actions integration with a ROS project
#

name: Build

on:
  push:
    branches: [main, jazzy]
  pull_request:

env:
  ARIACODA_PATH: ${{ github.workspace }}/ariacoda
  ARIACODA_URL: git@github.com:grupo-avispa/AriaCoda.git

jobs:
  install-ariacoda:
    runs-on: ubuntu-24.04
    steps:
      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: git
      - name: Cache ARIACODA
        id: cache-ariacoda
        uses: actions/cache@v4.2.0
        with:
          path: |
            ${{ env.ARIACODA_PATH }}
            /usr/local/lib
            /usr/local/include/Aria
          key: ariacoda-${{ runner.os }}-ubuntu-24.04
      - name: Install ARIACODA
        if: steps.cache-ariacoda.outputs.cache-hit != 'true'
        run: | 
          mkdir -p ${{ env.ARIACODA_PATH }} && cd ${{ env.ARIACODA_PATH }}
          git clone ${{ env.ARIACODA_URL }}
          cd ${{ env.ARIACODA_PATH }}/AriaCoda
          make install

  install-pioneer:
    runs-on: ubuntu-24.04
    needs: install-ariacoda
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.5
        with:
          required-ros-distributions: jazzy
      - name: Restore AriaCoda cache
        id: restore-cache-ariacoda
        uses: actions/cache@v4.2.0
        with:
          path: |
            ${{ env.ARIACODA_PATH }}
            /usr/local/lib
            /usr/local/include/Aria
          key: ariacoda-${{ runner.os }}-ubuntu-24.04
      - name: Build packages
        uses: ros-tooling/action-ros-ci@0.3.13
        with:
          package-name: |
            pioneer_ros2
            pioneer_common
            pioneer_core
            pioneer_aria
            pioneer_modules
            pioneer_msgs
          target-ros2-distro: jazzy
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc", "coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"]
              }
            }
          skip-tests: false
